### PR TITLE
Openshift Workability till upstream is fixed

### PR DESCRIPTION
**Pull request by waveywaves**
- blocks checks which stop workability of the operator due to validation fails due to dynamic nature of Openshift i.e. Setting security context, image pull secrets etc.
- Reversible change with only a few lines of code which need to be reverted.

### CODE REVIEW

**Comment by waveywaves** [comment]
Based on @otaviof review, need to move all the if/else check for isOpenshift ot a single block. As we move on this commit would be removed as upstream would work closely with moving validation to deployment controller instread of doing it themselves which incentivizes us to keep this as a temporary commit.

**Comment by otaviof** [comment]
Thanks @waveywaves! And thanks for sharing this here as well :-)

**Pull request merged**
